export default [[
  "<div class='story-message'>",
    "<div class='story-message-line1'>某日</div>",
    "<div class='story-message-line2'>打工仔如常上班</div>",
    "<div class='story-message-line3'>老闆突然召開開發部緊急會議</div>",
  "</div>",
],[
  "<div class='story-comic'>",
    "<img src='./images/story01.png' />",
    "<div class='story-comic-text-1-1'>為節省成本，公司決定炒咗電腦技術支援部門。嚟緊希望各位開發部同事拍硬檔幫幫手喇。都係電腦野啫。</div>",
  "</div>",
],[
  "<div class='story-message'>",
    "<div class='story-message-line1'>從此</div>",
    "<div class='story-message-line2'>開發部生活不一樣⋯⋯</div>",
  "</div>",
],[
  "<div class='story-comic'>",
    "<img src='./images/story02.jpg' />",
    "<div class='story-comic-text-2-1'>出嚟呀—！</div>",
    "<div class='story-comic-text-2-2'>幫我呀——</div>",
    "<div class='story-comic-text-2-3'>你個嘢壞咗呀！</div>",
    "<div class='story-comic-text-2-4'>死機呀——</div>",
    "<div class='story-comic-text-2-5'>我無得覆個客呀—！</div>",
    "<div class='story-comic-text-2-6'>你班ＩＴ狗快應門呀！</div>",
    "<div class='story-comic-text-2-7'>出嚟換碳粉盒呀！</div>",
    "<div class='story-comic-text-2-8'>幫我呀——</div>",
    "<div class='story-comic-text-2-9'>順便出嚟換水呀——！</div>",
    "<div class='story-comic-text-2-10'>渴撚死佢罷啦仆你個街！</div>",
    "<div class='story-comic-text-2-11'>試過reboot未呀冚家剷！</div>",
  "</div>",
],[
  "<div class='story-message'>",
    "<div class='story-message-line1'>公司產品開發進度嚴重受影響</div>",
    "<div class='story-message-line2'>開發部IT狗們終於按捺不住</div>",
    "<div class='story-message-line3'>找來老闆反映</div>",
  "</div>",
],[
  "<div class='story-comic'>",
    "<img src='./images/story03.jpg' />",
    "<div class='story-comic-text-3-1'>老闆⋯！</div>",
    "<div class='story-comic-text-3-2'>我好想專心寫程式⋯⋯</div>",
  "</div>",
]]
